Name = str(input("Enter your name :"))
Age = int(input("Enter your age :"))
marks = float(input("Enter your marks :"))
dob = str(input("Enter your date of birth :"))
Gender = str(input("Enter your gender :"))
nationality =str(input("Enter your nationality :"))
maritalStatus = str(input("Enter your marital status :"))
weight = float(input("Enter your weight :"))
height = float(input("Enter your height :"))
print("Hi",Name,Age,Gender,"your marks is",marks,"%. Your date of birth is",dob,"and You are",nationality,". you are ",maritalStatus,". Your height is ",height,"feet and weight is",weight,"kg.")